import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ai Faceswap Demo',
  description: 'Generated by Yousaf Sabir',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='body-bg-pattern'>{children}</body>
    </html>
  )
}
